spring:
  profiles:
    active: mydb # 기본 환경 선택

# local 환경
---
spring:
  profiles: mydb
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://smldb.czxi1b10dlvz.ap-northeast-2.rds.amazonaws.com:3306/todos_board?useSSL=false
    username: root
    password: password!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect